apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: h3rois5r9-java-springboot
  janus-idp.io/tekton: h3rois5r9-java-springboot
  backstage.io/kubernetes-id: h3rois5r9-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: h3rois5r9-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
